import type { Career } from "@/types/portfolio";

export const careers: Career[] = [
  {
    id: "1",
    company: "KIOT",
    position: "AI Engineer · Development PM · AX Engineer",
    startDate: "2024-05",
    isCurrent: true,
    summary: "AI 솔루션 개발부터 프로젝트 관리, 업무 자동화까지 다양한 역할을 수행하며 조직의 기술 역량과 운영 효율성을 향상시키고 있습니다.",
    roles: [
      {
        role: "AI Engineer",
        responsibilities: [
          "밀집인파 관제 시스템 개발 (Crowd Density Estimation)",
          "Edge AI 솔루션 개발 (NVIDIA Jetson, ODROID, DEEPX)",
          "Computer Vision 기반 영상 분석 솔루션 개발",
          "AI 모델 최적화 및 현장 배포",
        ],
      },
      {
        role: "Development PM",
        responsibilities: [
          "프로젝트 요구사항 정의 및 분석",
          "프로젝트 일정 관리 및 진행 상황 모니터링",
          "고객사 커뮤니케이션 및 요구사항 조율",
        ],
      },
      {
        role: "AX Engineer",
        responsibilities: [
          "AI Agent 및 생성형 AI 도구 도입과 활용 체계 설계",
          "Notion 기반 전사 업무 협업 플랫폼 설계 및 운영",
          "NAS 및 GitLab 기반 개발 자산 관리 체계 구축",
          "AI 기반 업무 자동화 프로세스 구축",
          "팀 협업 워크플로우 개선",
        ],
      },
    ],
    achievements: [
      "밀집인파 관제 시스템 현장 배포 및 Edge AI 솔루션 상용화",
      "AI Agent 기반 개발 프로세스 정립",
      "전사 업무 데이터베이스 구축 및 자동화 시스템 구축",
      "프로젝트 성공적 납품 및 고객 만족도 향상",
    ],
    techStack: [
      "Python",
      "PyTorch",
      "OpenCV",
      "NVIDIA Jetson",
      "Edge AI",
      "Notion API",
      "GitLab",
      "AI Agent",
      "Workflow Automation",
      "Project Management",
    ],
    projectIds: ["1", "2", "3", "5", "6"],
  },
  {
    id: "4",
    company: "포지큐브",
    position: "NLP Engineer",
    startDate: "2022-06",
    endDate: "2023-02",
    isCurrent: false,
    summary: "코로나19 시기 보건소·보험사 대상 음성 상담 서비스(STT → Normalization → Intent Classification → TTS)를 운영하는 회사에서 NLP 엔지니어로 근무했습니다. Intent Classification 단계에서 Azure 외부 API에 의존하고 있었으나, 의료·보험 특화 도메인 특성상 전문 용어 및 신조어 처리에 한계가 있었습니다. 이를 해결하기 위해 BERT 기반 Domain Adaptive Pre-training을 활용한 자체 Intent Classification 모델 개발 및 Azure API 대체를 담당했습니다.",
    roles: [
      {
        role: "NLP Engineer",
        responsibilities: [
          "Azure Intent Classification 대체를 위한 자체 모델 개발 주도",
          "의료·보험 도메인 Corpus 구축 및 전처리 파이프라인 설계",
          "BERT 기반 Domain Adaptive Pre-training (MLM) 수행으로 전문 용어·신조어 이해 능력 확보",
          "Intent Classification Task Fine-tuning 및 Classification Head 최적화",
          "Error Analysis 기반 오분류 패턴 분석 및 개선 실험",
          "A100 GPU 4장 활용 PyTorch DDP 분산 학습 환경 구축",
          "Mixed Precision Training 적용 및 학습 시간 최적화",
          "Azure 모델 대비 성능 비교 분석 및 자사 모델 전환 타당성 검토",
        ],
      },
    ],
    achievements: [
      "Azure Intent Classification API를 자체 BERT 모델로 대체하는 기술적 타당성 검증 및 전환 완료",
      "Domain Adaptive Pre-training으로 의료·보험 전문 용어·신조어 처리 능력 확보",
      "Intent 오분류율 감소 및 상용 서비스 적용 가능 수준까지 정확도 개선",
      "분산 학습 환경 구축(PyTorch DDP, Multi-GPU)으로 대규모 모델 학습 인프라 마련",
    ],
    techStack: [
      "Python",
      "PyTorch",
      "Hugging Face Transformers",
      "BERT",
      "Domain Adaptive Pre-training",
      "Fine-tuning",
      "PyTorch DDP",
      "Mixed Precision Training",
      "CUDA",
      "Multi-GPU Training",
      "Error Analysis",
      "Hyperparameter Optimization",
    ],
    projectIds: ["4"],
  },
  {
    id: "5",
    company: "비트캠프 강남본원",
    position: "AI 딥러닝 교육과정 수료",
    startDate: "2021-11",
    endDate: "2022-05",
    isCurrent: false,
    summary: "비트캠프 AI 딥러닝 교육과정을 이수하며 Python 기반 머신러닝 및 딥러닝, TensorFlow, PyTorch를 활용한 Computer Vision 및 자연어처리(NLP) 기술을 학습하였습니다. 졸업 프로젝트로 Scene Text OCR 기반 이미지 번역 서비스를 개발하여 논문 분석부터 실제 서비스 구현까지 전체 과정을 경험했습니다.",
    roles: [
      {
        role: "교육생",
        responsibilities: [
          "Python 기반 머신러닝 및 딥러닝 학습",
          "TensorFlow, PyTorch 프레임워크 활용",
          "Computer Vision 기술 학습 및 프로젝트 수행",
          "자연어처리(NLP) 기술 학습 및 프로젝트 수행",
          "모델 설계, 학습 및 성능 개선",
          "Scene Text OCR 기반 이미지 번역 서비스 졸업 프로젝트 수행",
        ],
      },
    ],
    achievements: [
      "AI 딥러닝 교육과정 수료",
      "Scene Text OCR 졸업 프로젝트 완료",
      "논문 분석부터 실제 구현까지 전체 개발 프로세스 경험",
      "머신러닝 및 딥러닝 기초 역량 확립",
    ],
    techStack: ["Python", "TensorFlow", "PyTorch", "Computer Vision", "NLP", "OCR"],
    projectIds: ["8"],
  },
];
