import type { Project } from "@/types/portfolio";

export const projects: Project[] = [
  {
    id: "1",
    slug: "notion-workspace",
    title: "Notion 기반 전사 협업 체계 구축",
    subtitle: "20인 규모 조직의 부서간 정보 파편화 해소 및 업무 데이터화",
    summary: "약 20명 규모의 회사에서 부서별로 분산된 도구(GitLab, NAS, CVAT, Figma, 네이버웍스, 엑셀)로 인한 정보 파편화와 협업 비효율을 파악하고, Notion을 전사 업무의 중심축으로 도입하여 부서 간 소통 구조와 업무 데이터 관리 체계를 재편했습니다.",
    categories: ["AX", "PROJECT_MANAGEMENT"],
    role: ["전사 업무 프로세스 분석", "Notion 도입 및 설계", "데이터베이스 구조 설계", "Notion API 자동화"],
    company: "KIOT",
    problem: "약 20명 규모의 조직이었지만 체계적인 업무 관리 시스템이 부재했습니다. 개발팀은 GitLab, 영업·기획팀은 NAS, 빅데이터팀은 CVAT, 디자인팀은 Figma, 전사 소통은 네이버웍스로 각각 분리되어 있었고, 업무 관리는 사실상 기능을 상실한 엑셀 시트에 의존하고 있었습니다. 이로 인해 부서 간 정보 단절과 협업 비효율이 누적되었고, 신규 입사자 온보딩이나 업무 이관 시 기준이 되는 문서나 히스토리가 없어 매번 구두로 전달해야 하는 상황이었습니다.",
    solution: "Notion을 단순 문서 도구가 아닌 전사 업무의 중심 허브로 도입했습니다. 각 부서가 사용하는 기존 도구(GitLab, NAS, CVAT, Figma, 네이버웍스)는 그대로 유지하면서, 프로젝트·업무·담당자·일정·문서를 Notion Database로 연결하여 부서를 막론하고 업무 현황을 한 곳에서 파악할 수 있는 구조를 만들었습니다. 기존 엑셀 기반 업무 관리는 Notion으로 전환하고, 신규 입사자 온보딩 및 업무 이관을 위한 회사 전반의 데이터화와 템플릿 표준화를 병행하여 전사적으로 지속 가능한 협업 프로세스를 구축했습니다.",
    responsibilities: [
      "부서별 업무 흐름 및 도구 사용 현황 분석(개발·영업·기획·빅데이터·디자인)",
      "Notion 전사 도입 기획 및 설계",
      "프로젝트·업무·담당자·일정·문서 Database 설계 및 Relation·Rollup 구조 구축",
      "기존 엑셀 기반 업무 관리 데이터의 Notion 전환",
      "GitLab, NAS, CVAT, Figma, 네이버웍스 등 기존 도구와의 연동 구조 설계",
      "신규 입사자 온보딩 및 업무 이관을 위한 표준 템플릿 및 가이드 문서 작성",
      "Notion API 기반 반복 업무 자동화",
      "전사 구성원 대상 사용 교육 및 운영 정책 수립",
    ],
    achievements: [
      "부서별로 분산되어 있던 업무 정보를 Notion 중심으로 통합하여 전사 협업 체계 구축",
      "신규 입사자 온보딩 및 업무 이관 시 기준 문서 및 히스토리 확보",
      "엑셀 기반 업무 관리를 Notion으로 전환하여 실질적인 업무 추적 가능",
      "Notion API 자동화로 반복 업무 효율화",
    ],
    techStack: ["Notion", "Notion API", "Python"],
    thumbnailImage: "/images/projects/notion-workspace/dashboard.png",
    gallery: [
      {
        src: "/images/projects/notion-workspace/schedule.png",
        caption: "팀별 업무 현황 — 담당자별 주간 태스크와 스프린트 진행 상황을 Notion DB로 통합 추적",
      },
      {
        src: "/images/projects/notion-workspace/milestone.png",
        caption: "전사 프로젝트 타임라인 — 부서 구분 없이 모든 프로젝트의 마일스톤과 일정을 단일 뷰에서 파악",
      },
    ],
    isFeatured: true,
    displayOrder: 1,
    visibility: "PUBLIC",
  },
  {
    id: "2",
    slug: "ai-agent-adoption",
    title: "전사 AI Agent 도입 및 개발 프로세스 체계화",
    subtitle: "Claude Code 팀 도입부터 Harness Engineering 기반 활용 체계 구축까지",
    summary: "개발자들의 AI Agent 활용 현황을 점검하고 비효율 구조를 개선하기 위해, 주간 스터디 운영과 Claude Code 전사 도입을 주도하여 AI 기반 개발 프로세스를 체계화했습니다.",
    categories: ["AX"],
    role: ["AI Agent 전사 도입 기획", "주간 스터디 운영", "Harness Engineering 체계 설계"],
    company: "KIOT",
    problem: "개발자들이 자발적으로 AI Agent를 쓰기 시작했지만 단순 질의·응답 수준에 그쳤습니다. 프롬프트 작성이나 컨텍스트 구성에 대한 이해 없이 도구만 늘어난 상황이었고, AI를 써도 개발 생산성의 실질적인 변화를 체감하기 어려웠습니다.",
    solution: "두 방향으로 접근했습니다. 역량 측면에서는 매주 AI Agent 스터디를 기획·운영하여 Prompt Engineering 기초부터 Context Engineering, Harness Engineering까지 단계적으로 팀 전체의 활용 수준을 높였습니다. 환경 측면에서는 Claude Code 팀 계정 도입을 회사에 건의하여 전 개발자가 공식적으로 사용할 수 있는 체계를 마련했습니다. 업무 유형별 AI 활용 방식과 리뷰 기준을 함께 정의해 지속 가능한 프로세스로 정착시켰습니다.",
    responsibilities: [
      "개발자 AI 활용 현황 파악 및 비효율 구조 분석",
      "주간 AI Agent 스터디 기획·운영 (Prompt Engineering → Context Engineering → Harness Engineering)",
      "Claude Code 팀 계정 도입 건의 및 전사 도입 주도",
      "업무 유형별 AI 활용 워크플로우 정의",
      "AI 생성 코드·문서 리뷰 체계 설계",
      "개발팀 대상 AI 활용 가이드 작성 및 배포",
    ],
    achievements: [
      "Claude Code 팀 계정 전사 도입으로 전 개발자 AI Agent 공식 활용 환경 구축",
      "주간 스터디로 팀 AI 활용 수준 고도화",
      "AI 기반 개발 프로세스 정립으로 반복 업무 효율화",
    ],
    techStack: ["Claude Code", "Cursor", "Prompt Engineering", "Context Engineering", "Harness Engineering"],
    isFeatured: true,
    displayOrder: 2,
    visibility: "PUBLIC",
  },
  {
    id: "3",
    slug: "crowd-monitoring",
    title: "3D Reconstruction 기반 공간 밀집인파 관제 시스템",
    subtitle: "BEV 좌표 투영으로 원근 왜곡을 제거한 실제 공간 단위 군중 밀도 분석",
    summary: "기존 YOLO/Density Estimation 기반 관제의 근본 한계인 2D 카메라 원근 왜곡 문제를 해결하기 위해, 3D Reconstruction과 BEV(Bird's-Eye View) 투영을 결합한 공간 기반 밀집도 분석 시스템을 연구·개발하고 실서비스에 적용했습니다.",
    categories: ["COMPUTER_VISION", "EDGE_AI"],
    role: ["시스템 연구·설계", "Crowd Density Estimation 모델 개발", "3D Reconstruction·BEV 파이프라인 구현", "개발 PM"],
    company: "KIOT",
    problem: "기존 YOLO 기반 Object Detection 및 Density Estimation 기반 Crowd Counting은 모두 2D Camera View를 기준으로 분석하기 때문에, 카메라와의 거리·촬영 각도에 따라 동일한 영상 영역이라도 실제 커버하는 면적이 달라지는 원근 왜곡 문제가 존재합니다. 이로 인해 화면상의 사람 수나 Density Map만으로는 \"실제 공간 1m²당 몇 명이 있는가\"와 같은 절대적인 밀집도를 정확하게 산출하기 어렵습니다.",
    solution: "현장 공간을 3D Reconstruction하여 실제 공간 구조를 복원하고 생성된 3D Point Cloud를 BEV 좌표계로 변환했습니다. Camera View와 3D Reconstruction 공간 간의 좌표 관계를 Alignment·매핑하여 Crowd Density Estimation 모델의 밀도 정보를 BEV 공간으로 투영함으로써 원근 왜곡을 제거했습니다. 이후 BEV상의 고밀도 영역을 공간적으로 Clustering하여 실제 군중이 형성된 영역과 면적·밀도를 분리 산출하도록 설계했습니다. 전체 파이프라인은 다음과 같습니다: Camera View → Crowd Density Estimation → Camera–3D Alignment → BEV Projection → Spatial Density Mapping → Density Clustering → Congestion Detection",
    responsibilities: [
      "Crowd Density Estimation 모델 개발 및 데이터셋 구성·Annotation 기준 수립",
      "현장 공간 3D Reconstruction 및 BEV 좌표계 생성",
      "Camera View와 3D 공간 간 Alignment·매핑 구현",
      "Density Map의 BEV 공간 투영 및 Spatial Density Mapping 구현",
      "BEV 상 고밀도 군집 영역 Clustering 및 면적·밀도 산출 로직 개발",
      "Edge AI 환경 모델 최적화 및 관제 서버 연동",
      "현장 테스트·성능 검증 및 고객사 커뮤니케이션·일정 관리",
    ],
    achievements: [
      "단순 인원 계수를 넘어 실제 공간 면적 기반 군중 밀집도 및 고밀도 군집 영역 탐지 시스템 연구·개발 및 실서비스 적용",
      "Camera View 원근 왜곡 제거로 공간 단위 절대 밀집도 산출 가능",
      "관제 화면·알림 시스템 연동 완료",
    ],
    techStack: ["Python", "PyTorch", "OpenCV", "3D Reconstruction", "BEV Projection", "Spatial Clustering", "NVIDIA Jetson"],
    gallery: [
      {
        src: "/images/projects/crowd-monitoring/pipeline.png",
        caption: "전체 파이프라인 — Camera View에서 Crowd Density Estimation, 3D Alignment, BEV Projection, Spatial Clustering, Congestion Detection까지의 시스템 구조",
        fit: "contain" as const,
      },
    ],
    isFeatured: true,
    displayOrder: 3,
    visibility: "PUBLIC",
  },
  {
    id: "4",
    slug: "intention-classification",
    title: "도메인 특화 BERT 기반 Intent Classification 모델 개발",
    subtitle: "Domain Adaptive Pre-training 기반 의료·보험 도메인 의도 분류",
    summary: "코로나19 시기 보건소·보험사 상담 서비스에서 범용 언어모델이 의료·보험 전문 용어와 신조어를 이해하지 못하는 문제를 Domain Adaptive Pre-training과 분산 학습 환경을 통해 해결했습니다.",
    categories: ["NLP"],
    role: ["NLP 모델 개발", "Domain Adaptive Pre-training", "분산 학습 환경 구축"],
    company: "포지큐브",
    problem: "범용 BERT 모델이 의료·보험 분야의 전문 용어, 코로나 관련 신조어, 상담 문체 등을 학습하지 못해 특정 Intent 간 오분류가 빈번하게 발생했습니다.",
    solution: "자체 구축한 의료·보험 도메인 Corpus를 활용하여 BERT에 Domain Adaptive Pre-training(MLM)을 수행하고, Intent Classification Task에 Fine-tuning을 적용했습니다. A100 GPU 4장을 활용한 PyTorch DDP 분산 학습 환경을 구축하여 대규모 모델 학습을 효율화했습니다.",
    responsibilities: [
      "의료·보험 도메인 Corpus 구축 및 전처리 파이프라인 설계",
      "BERT 기반 Domain Adaptive Pre-training (MLM) 수행",
      "Intent Classification Task Fine-tuning 및 Classification Head 최적화",
      "Error Analysis 기반 오분류 패턴 분석 및 개선 실험",
      "A100 GPU 4장 활용 PyTorch DDP 분산 학습 환경 구축",
      "Mixed Precision Training 적용 및 학습 시간 최적화",
      "하이퍼파라미터 튜닝 (Learning Rate, Batch Size, Warmup Steps)",
      "기존 외부 모델 대비 성능 비교 분석 및 전환 타당성 검토",
    ],
    achievements: [
      "도메인 특화 BERT 모델 개발로 의료·보험 용어 이해도 향상",
      "Intent 오분류율 감소 및 서비스 적용 가능 수준까지 정확도 개선",
      "자사 모델 전환 검토 완료 및 기술적 타당성 검증",
      "분산 학습 환경 구축으로 대규모 모델 학습 경험 확보",
    ],
    techStack: [
      "Python",
      "PyTorch",
      "Hugging Face Transformers",
      "BERT",
      "Domain Adaptive Pre-training",
      "Fine-tuning",
      "PyTorch DDP",
      "Mixed Precision Training",
      "CUDA",
      "Multi-GPU Training",
      "Error Analysis",
      "Hyperparameter Optimization",
    ],
    isFeatured: true,
    displayOrder: 4,
    visibility: "PUBLIC",
  },
  {
    id: "5",
    slug: "nas-gitlab-infrastructure",
    title: "NAS 및 GitLab 기반 개발 자산 관리 체계 구축",
    subtitle: "코드, 모델, 데이터 관리 인프라 구축",
    summary: "개발팀의 코드와 조직 문서가 지속적으로 축적되고 추적·인수인계될 수 있도록 NAS와 GitLab 기반의 개발 자산 관리 체계를 구축했습니다.",
    categories: ["PROJECT_MANAGEMENT"],
    role: ["개발 인프라 구축", "버전 관리 체계 정립"],
    company: "KIOT",
    problem: "분산되어 있던 코드, 모델, 데이터, 개발 문서 및 회사 자료의 체계적인 관리가 필요했습니다.",
    solution: "사내 NAS와 GitLab을 운영하고 관리 기준을 수립했습니다.",
    responsibilities: [
      "GitLab 프로젝트 및 Repository 구조 관리",
      "코드 버전 관리 체계 정립",
      "Branch 및 Merge Request 운영 기준 정리",
      "프로젝트와 조직별 접근 권한 관리",
      "NAS 폴더 및 문서 분류 구조 설계",
      "모델 가중치, 데이터셋 및 배포 산출물 관리",
      "프로젝트 생성, 운영, 종료 및 인수인계 체계 정리",
      "백업 및 개발 자산 관리 프로세스 운영",
    ],
    achievements: [
      "개발 자산 관리 체계 구축 완료",
      "코드 및 문서 추적·인수인계 가능",
    ],
    techStack: ["GitLab", "NAS", "Docker"],
    isFeatured: false,
    displayOrder: 5,
    visibility: "PUBLIC",
  },
  {
    id: "6",
    slug: "edge-ai-solution",
    title: "Edge AI 솔루션 개발",
    subtitle: "NVIDIA Jetson, ODROID, DEEPX 기반 영상 분석",
    summary: "다양한 현장 환경에서 AI 모델을 독립적으로 실행할 수 있도록 Edge Device 기반의 영상 분석 솔루션을 개발했습니다.",
    categories: ["EDGE_AI", "COMPUTER_VISION"],
    role: ["Edge AI 솔루션 개발", "모델 최적화", "현장 배포"],
    company: "KIOT",
    problem: "현장 환경에서 AI 모델을 독립적으로 실행해야 하는 요구사항이 있었습니다.",
    solution: "NVIDIA Jetson, ODROID, DEEPX 장비 기반의 영상 분석 솔루션을 개발했습니다.",
    responsibilities: [
      "장비별 AI 모델 실행 환경 구성",
      "영상 입력 및 실시간 추론 파이프라인 개발",
      "장치 성능에 맞춘 모델 변환과 최적화",
      "Edge Device와 중앙 서버 간 데이터 연동",
      "추론 결과, 이미지 및 장비 상태 전송",
      "현장 설치와 장애 대응",
      "장비별 호환성 및 성능 검증",
    ],
    achievements: [
      "다양한 Edge Device 환경 지원",
      "실시간 영상 분석 파이프라인 구축",
    ],
    techStack: ["Python", "PyTorch", "TensorRT", "NVIDIA Jetson", "ODROID", "DEEPX"],
    thumbnailImage: "/images/projects/edge-ai-solution/thumbnail.png",
    isFeatured: false,
    displayOrder: 6,
    visibility: "PUBLIC",
  },
  {
    id: "7",
    slug: "spacehong",
    title: "Spacehong 공연장 웹서비스 풀스택 개발",
    subtitle: "홍대 최대 규모 공연장 예약 시스템 구축",
    summary: "홍대에서 가장 유명한 공연장 중 하나인 Spacehong의 공식 웹사이트를 설계부터 배포까지 전체 개발을 담당했습니다. React 기반 프론트엔드와 Node.js 백엔드, 그리고 Vercel, Render, Supabase를 활용한 인프라 구성으로 실시간 예약 관리 시스템을 구현했습니다.",
    categories: ["WEB"],
    role: ["풀스택 개발", "인프라 구축", "서비스 기획"],
    problem: "홍대 대표 공연장인 Spacehong이 고객 예약 관리와 공간 정보 제공을 위한 체계적인 웹 플랫폼이 필요했습니다. 실시간 예약 접수, 고객 문의 처리, 공연 일정 관리 등을 효율적으로 처리할 수 있는 시스템이 요구되었습니다.",
    solution: "React와 TypeScript 기반의 SPA(Single Page Application)로 사용자 인터페이스를 구현하고, Node.js 백엔드로 예약 관리 API를 개발했습니다. Vercel을 통한 프론트엔드 배포, Render를 활용한 백엔드 서버 운영, Supabase를 통한 데이터베이스 및 인증 관리로 안정적인 서비스 인프라를 구축했습니다. 예약 요청 시 자동 이메일 발송 시스템을 구현하여 고객과 관리자 간 실시간 커뮤니케이션을 지원했습니다.",
    isSolo: true,
    responsibilities: [
      "서비스 기획 및 요구사항 정의",
      "React + TypeScript 기반 프론트엔드 전체 개발",
      "반응형 UI/UX 디자인 및 구현",
      "Node.js 백엔드 API 서버 개발",
      "예약 관리 시스템 설계 및 구현",
      "고객 예약 시 자동 이메일 발송 기능 구현",
      "Supabase 데이터베이스 스키마 설계 및 연동",
      "Vercel, Render를 활용한 배포 및 인프라 구축",
      "실시간 예약 상태 관리 시스템 구현",
      "관리자 대시보드 개발",
      "서비스 운영 및 지속적인 유지보수",
      "고객 피드백 기반 기능 개선",
    ],
    achievements: [
      "홍대 대표 공연장 공식 웹사이트 전체 구축 완료",
      "실시간 예약 관리 시스템 상용화",
      "자동 이메일 발송 시스템 구현으로 고객 응대 효율화",
      "Vercel + Render + Supabase 기반 안정적인 서비스 운영",
      "React + Node.js 풀스택 개발 경험 확보",
    ],
    techStack: [
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Node.js",
      "Express",
      "Supabase",
      "Vercel",
      "Render",
      "Email Automation",
    ],
    thumbnailImage: "/images/projects/spacehong/thumbnail.png",
    externalUrl: "https://www.space-hong.com/",
    isFeatured: false,
    displayOrder: 7,
    visibility: "PUBLIC",
  },
  {
    id: "8",
    slug: "ocr-scene-text",
    title: "Scene Text OCR 기반 이미지 번역 서비스",
    subtitle: "자연환경 문자 인식 및 번역 시스템",
    summary: "문서가 아닌 자연환경(Scene Text)의 텍스트를 인식하고 번역하는 OCR 서비스를 개발했습니다. EAST 기반 Detection과 Recognition을 분리한 파이프라인 구조로 실제 거리의 간판, 메뉴판 등에서 높은 정확도를 달성했습니다.",
    categories: ["COMPUTER_VISION"],
    role: ["OCR 모델 개발", "Detection & Recognition 파이프라인 설계"],
    company: "비트캠프 강남본원",
    problem: "기존 OCR은 정형화된 문서에서는 높은 정확도를 보이지만, 실제 거리의 간판이나 메뉴판 같은 Scene Text에서는 다양한 배경, 조명, 회전된 문자로 인해 정확도가 크게 저하되는 문제가 있었습니다.",
    solution: "Text Detection과 Recognition을 분리하여 접근했습니다. Detection 단계에서는 Scene Text에 특화된 EAST 모델을 적용하고, Recognition 단계에서는 검출된 텍스트 영역을 개별적으로 인식하는 구조를 설계했습니다. 각 모듈을 독립적으로 개선할 수 있도록 모듈화하여 시스템 전체의 유지보수성을 높였습니다.",
    responsibilities: [
      "OCR 논문 분석 및 EAST 모델 구조 이해",
      "Scene Text Detection 모델 구현",
      "데이터셋 구축 및 전처리 파이프라인 설계",
      "Detection 결과 후처리 및 Recognition 연계",
      "Detection-Recognition 통합 파이프라인 구성",
      "번역 API 연동 및 End-to-End 서비스 구현",
      "모델 학습 및 성능 평가",
      "전체 시스템 설계 및 구현",
    ],
    achievements: [
      "Scene Text Detection 및 Recognition 파이프라인 구축",
      "Detection과 Recognition 모듈 분리로 독립적 성능 개선 가능",
      "이미지 입력부터 번역 결과까지 End-to-End 서비스 구현",
      "논문 분석부터 실제 구현까지 전체 과정 경험",
      "시스템 설계 관점의 AI 서비스 개발 역량 확보",
    ],
    lessonsLearned: "이 프로젝트를 진행하며 논문을 읽고 구현하는 과정이 실제 서비스 개발과는 다르다는 점을 배웠습니다. 모델의 구조를 이해하는 것뿐 아니라 데이터 품질, 전처리, 파이프라인 구성, 후처리 방식 등이 전체 성능에 큰 영향을 미친다는 것을 경험했습니다.\n\n이후 프로젝트에서는 단순히 모델 자체의 성능뿐 아니라 시스템 전체를 설계하는 관점으로 문제를 바라보게 되었으며, 이러한 경험은 이후 NLP, Computer Vision, Edge AI, RAG 시스템을 개발하는 기반이 되었습니다. Detection과 Recognition을 분리하여 각각을 독립적으로 개선할 수 있도록 설계한 경험은 이후 프로젝트에서 모듈화와 관심사의 분리(Separation of Concerns) 원칙을 적용하는 데 큰 도움이 되었습니다.",
    techStack: [
      "Python",
      "TensorFlow",
      "PyTorch",
      "OpenCV",
      "EAST",
      "OCR",
      "Computer Vision",
      "Scene Text Detection",
      "Text Recognition",
    ],
    isFeatured: false,
    displayOrder: 8,
    visibility: "PUBLIC",
  },
];
